---
platform: linux

image: docker:///cloudfoundry/cf-mysql-ci

inputs:
  - name: streaming-mysql-backup-tool
    path: gopath/src/streaming-mysql-backup-tool

run:
  path: gopath/src/streaming-mysql-backup-tool/ci/scripts/unit-tests
